# Generated by Django 2.2.5 on 2019-09-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_oddam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(max_length=500)),
                ('type', models.CharField(choices=[('f', 'fundacja'), ('o', 'organizacja pozarzdowa'), ('z', 'zbiorka lokalna')], default='fundacja', max_length=30)),
                ('categories', models.ManyToManyField(to='app_oddam.Category')),
            ],
        ),
    ]
