# Generated by Django 2.2.5 on 2019-10-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_oddam', '0003_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='type',
            field=models.CharField(choices=[('f', 'fundacja'), ('o', 'organizacja pozarzadowa'), ('z', 'zbiorka lokalna')], default='fundacja', max_length=30),
        ),
    ]
